#!/bin/sh
EVENT_GROUP="INSTR_RETIRED_ANY:FIXC0,FP_ARITH_INST_RETIRED_128B_PACKED_DOUBLE:PMC0,FP_ARITH_INST_RETIRED_SCALAR_DOUBLE:PMC1,FP_ARITH_INST_RETIRED_256B_PACKED_DOUBLE:PMC2,FP_ARITH_INST_RETIRED_512B_PACKED_DOUBLE:PMC3"
RANK=$1
likwid-perfctr -t 100ms -C N:0 -g $EVENT_GROUP ./amg -n 100 100 100 -P 2 2 5 2> amg_dp_$RANK.txt